export const WEEKLY_VIEW='weekly_view';
export const FORTNIGHTLY_VIEW='fortnightly_view';
export const MONTHLY_VIEW='monthly_view';
export const QUARTERLY_VIEW='quarterly_view';
export const CALENDAR_MODE='calendar_mode';
export const COMPARE_MODE='compare_mode';
export const DEALS_MODE='deals_mode';
export const APPLICATION_MODE='application_mode';
export const LIKED_MODE='liked_mode';
export const PROPOSAL_MODE='proposal_mode';
export const FEATURES='features';
export const RATES_AND_FEES='rates_and_fees';
export const DISCOUNTS_AND_OFFERS='discounts_and_offers';
export const SPECIAL_REQUIREMENTS='special_requirements';
export const REQUIRED_DOCS='required_docs';
export const FILTER_NONE = 'none';
export const FILTER_LIKED = 'liked';
export const FILTER_DATE = 'date';
export const FILTER_LENDER = 'lender';
export const FILTER_BROKER = 'broker';
export const LODGEMENT_VIEW = 'lodgement_view';
export const UNDER_ASSESSMENT_VIEW = 'under_assessment_view';
export const CONDITIONALLY_APPROVED_VIEW = 'conditionally_approved_view';
export const CLOSED_OR_EXPIRED_VIEW = 'closed_or_expired_view';
export const PROPOSAL_RECIEVED_ON = 'Received on '
export const PROPOSAL_REFERENCE = 'Reference  '